CATEGORIA_PADRAO = "geral"
CATEGORIAS_VALIDAS = ["informatica", "moveis", "vestuario", CATEGORIA_PADRAO, "eletronicos", "livros"]

STATUS_PENDENTE = "pendente"
STATUS_APROVADO = "aprovado"
STATUS_ENVIADO = "enviado"
STATUS_ENTREGUE = "entregue"
STATUS_CANCELADO = "cancelado"
STATUS_PEDIDO_VALIDOS = [STATUS_PENDENTE, STATUS_APROVADO, STATUS_ENVIADO, STATUS_ENTREGUE, STATUS_CANCELADO]

NOME_PRODUTO_MIN_LENGTH = 2
NOME_PRODUTO_MAX_LENGTH = 200

DESCONTO_FAIXA_1_LIMIAR = 10000
DESCONTO_FAIXA_1_TAXA = 0.10
DESCONTO_FAIXA_2_LIMIAR = 5000
DESCONTO_FAIXA_2_TAXA = 0.05
DESCONTO_FAIXA_3_LIMIAR = 1000
DESCONTO_FAIXA_3_TAXA = 0.02
